# Generated by Django 3.2.8 on 2021-10-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreedDog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Порода собаки',
                'verbose_name_plural': 'Породы собак',
            },
        ),
        migrations.CreateModel(
            name='HatiMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.JSONField(default=list, verbose_name='Животное')),
                ('tail', models.JSONField(default=list, verbose_name='Хвост')),
                ('color', models.JSONField(default=list, verbose_name='Цвет')),
                ('breed', models.ManyToManyField(to='hati.BreedDog', verbose_name='Породы')),
            ],
        ),
    ]
