# Generated by Django 3.2.8 on 2021-10-24 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hati', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.IntegerField(choices=[(1, 'Собака')], verbose_name='Животное')),
                ('tail', models.IntegerField(choices=[(1, 'Длинный'), (2, 'Короткий'), (3, 'Нет хвоста')], verbose_name='Хвост')),
                ('color', models.IntegerField(choices=[(1, 'Светлая'), (2, 'Тёмная'), (3, 'Многоцветная')], verbose_name='Цвет')),
                ('image', models.ImageField(upload_to='hati', verbose_name='Изображение')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hati.breeddog', verbose_name='Порода')),
            ],
        ),
    ]
