# Generated by Django 3.2.8 on 2021-10-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hati', '0002_hati'),
    ]

    operations = [
        migrations.AddField(
            model_name='hati',
            name='camera',
            field=models.CharField(default=1, max_length=50, verbose_name='Номер комеры'),
            preserve_default=False,
        ),
    ]
