# Generated by Django 3.2.8 on 2021-10-25 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hati', '0003_hati_camera'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hati',
        ),
    ]
