# Generated by Django 3.2.8 on 2021-10-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hati', '0004_delete_hati'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hatimeta',
            name='breed',
        ),
        migrations.AddField(
            model_name='hatimeta',
            name='breed',
            field=models.JSONField(default=list, verbose_name='Порода'),
        ),
        migrations.DeleteModel(
            name='BreedDog',
        ),
    ]
